services:
  no-q:
    image: node:20
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5173:5173
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: no-q
      POSTGRES_USER: no-q
      POSTGRES_PASSWORD: password
    command: bash -c "npm run dev -- --host"
  
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: no-q
      POSTGRES_USER: no-q
      POSTGRES_PASSWORD: password
  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
